[project]
name = "dfa-samplers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dfa>=4.7.1",
    "dfa-mutate>=0.1.3",
]
